[build-system]
requires = ["networkx"]
build-backend = "flit_core.buildapi"

[project]
name = "Thompson's Group F"
authors = [{name = "Anders", email = "accornect@mun.ca"}]
dynamic = ["version", "description"]
